twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [
        'bootstrap_4_layout.html.twig',
        'form/email_theme.html.twig'
    ]
    paths:
        '%kernel.project_dir%/public/images': images
        '%kernel.project_dir%/public/css': styles

when@test:
    twig:
        strict_variables: true
